name: Phoebus build

on: 
  push:
    branches-ignore:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up maven action
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: '17'
        maven-version: '3.9.6'
    - name: Build
      run: mvn --batch-mode install -DskipTests
